@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(user, "Utilisateur", "Un Utilisateur du systeme de gestion flux.")
System_Boundary(ibs, "Systeme de gestion de flux") {
    Container(spa, "Single Page Application", "Angular 12", "Fournir toutes les fonctionalites a l'utilisateurs via le navigateur")
    Container(db, "Base de donnees", "MongoDb", "[SGBD] \n Stocker les donnees du systeme de facons permanentes .")
    Container(api, "API ", "Express", "Fournir toutes les fonctionalites via JSON/HTTP API.")


    BiRel(api, db, "Lire et Ecrire","Mongoose Driver")
    BiRel(spa, api, "Utiliser", "JSON/HTTPS")
}
 Container_Ext(c_ext, "Flux RSS", "XML", "Fournir le flux RSS via XML.",HTTPS)
BiRel(user, spa, "Utiliser", "HTTPS")
Rel(api, c_ext, "Recuperer le flux RSS", "XML/HTTPS")
@enduml
